# -*- coding: utf-8 -*-
"""wineclassificationusingSVM0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Sdxeh7ahU2WdSN7WOYS7kreaEh7MS_IQ
"""

import sklearn
from sklearn import datasets
from sklearn import svm as svm
from sklearn import metrics

wine=datasets.load_wine();
print(wine.feature_names); 
print(wine.target_names);

x=wine.data
y=wine.target 
x_train,x_test,y_train,y_test=sklearn.model_selection.train_test_split(x,y,test_size=0.2)
print(x_train,y_train);

clf=svm.SVC(kernel="linear") 
clf.fit(x_train,y_train) 
y_pred=clf.predict(x_test)
acc=metrics.accuracy_score(y_test,y_pred); 
print(acc);